name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -scheme ALHelper -destination generic/platform=iOS
    - name: Run tests
      run: xcodebuild test -scheme ALHelper -destination "name=iPhone 12 Pro Max,OS=15.2"
